language: node_js
node_js: stable
before_install:
  - wget https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
script:
  - npm start
after_script:
  - git config user.name "infoscope"
  - git config user.email "infoscope@qq.com"
  - git commit -am "build gfwlist"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/info-scope/gfwlist.git" master:master